### ISSUE TITLE
Markdown rendering for messages

### ISSUE THREAD

**Issue by edfletcher** [nhexirc/nhex#42]
Should be feature-flagged

Maybe only the subset of Markdown people normally use on IRC? Don't think we want `# Something` to turn into

# Something

That's a bit _too_ loud.

**Comment by terrablue** [comment]
[e53eb6c](https://github.com/nhexirc/nhex/commit/e53eb6c2393393e7761911bdaf13d51dad5b989c)

**Comment by vxgxbxnd** [comment]
Markdown integrated via blue's commit.
