### ISSUE TITLE
Auto-link URLs

### ISSUE THREAD

**Issue by edfletcher** [nhexirc/nhex#5]
Should be feature-flagged

**Comment by edfletcher** [comment]
@PantelicGR this might be a great issue for you to start with: is contained entirely to the frontend, will definitely require some messing around with React (may want to create a `MessageBoxLine` component that encapsulates the presentation of a single line, which may be helpful in the future as well, such as for #26). Let me know if you'd like to take a crack at it! 👍

**Comment by edfletcher** [comment]
You'll also need to pull in and consume a library for the URL detection: I've used [extract-urls](https://www.npmjs.com/package/extract-urls) in the past [with DRC](https://github.com/discord-relay-chat/drc/commit/aeda423ba00bfb7da82774523c51c35d1a198881) to great success.

**Comment by PantelicGR** [comment]
I'm still learning web-development so I don't know if I can do it right now.
If I get a chance when I'm ready I will take a look into Nhex's source code and see what I can do to help.

**Comment by edfletcher** [comment]
Resolved by https://github.com/nhexirc/nhex/commit/f1508bfba17d7f53d58ea3b809a77a6b6e48770a
