### ISSUE TITLE
Responsive UI

### ISSUE THREAD

**Issue by edfletcher** [nhexirc/nhex#9]
The UI has hardcoded sizes right now. That's not good, at all.

**Comment by gnprwx** [comment]
I can definitely fix this on the front-end. I would expect this to translate fine to the client program itself, but I'll have to just try it first.

You can assign this to me.

**Comment by edfletcher** [comment]
You rock @gnprwx, thank you a ton for volunteering! Was definitely hoping you might 😊, your website is incredible so I _know_ you've got the chops for it! 🚀

**Comment by gnprwx** [comment]
Responsive design will happen at the same time as creating the base theme, so this will end up being a duplicate issue.

See: https://github.com/nhexirc/client/issues/27

**Comment by gnprwx** [comment]
I'll be tackling this next, but under a branch.
