### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by edfletcher** [nhexirc/nhex#99]
👍 if you're in favor of the idea

**Comment by edfletcher** [comment]
```
nhex/
├─ site/
├─── docs/
├─ client/
```

**Comment by terrablue** [comment]
I think the usual structure, if we were to use `yarn / pnpm / bun` for monorepo management, would be `packages/{site,client}`. That being said, this is probably more relevant in case you have codependencies within your monorepo, which isn't the case with the current planned two packages.

**Comment by zvxvx** [comment]
> I think the usual structure, if we were to use `yarn / pnpm / bun` for monorepo management, would be `packages/{site,client}`. That being said, this is probably more relevant in case you have codependencies within your monorepo, which isn't the case with the current planned two packages.

I used your suggested structure for future proofing.
